from artwork_utils import save_artwork
from general_utils import copy_dir
from genre_utils import update_genre


if __name__ == '__main__':
    use_temp_dir = False
    save_art = False
    correct_genre = True
    rootdir = r"/home/jimmy/Desktop/Jellyfin"
    tempdir = r"/home/jimmy/Desktop/temp"

    if use_temp_dir:
        copy_dir(rootdir, tempdir)
        rootdir = tempdir

    if save_art:
        save_artwork(rootdir)

    if correct_genre:
        corrections = {'Avantgarde': 'Avant-garde',
                'Ambient Techno\x00Dub Techno\x00Techno\x00EDM': 'Ambient Techno/Electronic',
                'Minimal Techno': 'Techno/Electronic',
                'Techno\x00': 'Techno/Electronic',
                'Jazz Vocals': 'Jazz',
                'Pop-Rock': 'Pop',
                'Electronica;Dance': 'Electronic',
                'Synth-pop': 'Synth-Pop',
                'Anarcho-Punk': 'Anarcho-Punk',
                'Gothic Rock': 'Goth',
                'Glitch; Minimal Techno; Ambient Dub': 'Glitch/Ambient Techno/Electronic',
                'Rap': 'Hip-Hop',
                'New Age, Pop Rock': 'New Age/Pop-Rock',
                'Indonesian': 'Indonesian Pop',
                'Techno Dub': 'Techno/Electronic',
                'Twee': 'Twee Pop',
                'Goth Rock': 'Goth',
                'Dub Techno': 'Electronic',
                'Chiptune': 'Electronic',
                'Gothic': 'Goth',
                'Synth': 'Electronic',
                'IDM, Electronic': 'IDM/Electronic',
                'Fusion': 'Jazz Fusion',
                'Hardcore Techno': 'Techno/Electronic',
                'Electro, Tech House': 'Electronic/House',
                'Dance And Electronica': 'Electronic',
                'Tech House': 'Electronic/House',
                'Tech House ': 'Electronic/House',
                ' IDM ': 'IDM',
                'slowcore': 'Slowcore',
                'Pop Punk': 'Pop-Punk',
                'Modern Classical': 'Contemporary Classical',
                'Post Punk': 'Post-Punk',
                'Electro': 'Electronic',
                'Noise Pop': 'Noise Rock',
                'Classic Rock': 'Rock',
                'Downtempo': 'Electronic',
                'Indie-Rock': 'Indie Rock',
                'Hardcore Punk': 'Hardcore/Punk',
                'Classical\x00\ufeffModern\x00\ufeffMinimalism\x00\ufeffPercussion\x00\ufeffOrange Mountain Music': 'Contemporary Classical',
                'Shoegaze\x00Twee Pop\x00Dream Pop': 'Shoegaze/Dream Pop',
                'Synth Pop': 'Synth-Pop',
                'Shoegazer': 'Shoegaze',
                'Dance': 'Electronic',
                'Electronica': 'Electronic',
                'IDM\x00Downtempo': 'IDM',
                'Indie Pop\x00Indietronica': 'Indie Pop',
                'Techno, Minimal, Deep House': 'Techno/Electronic/Deep House',
                'Hip Hop': 'Hip-Hop',
                'Dream Pop, Shoegaze, Post-Rock': 'Dream Pop/Shoegaze/Post-Rock',
                'Breakcore': 'Electronic/Breakcore',
                'African Blues': 'African/Blues',
                'Japanese Folk': 'Japanese/Folk',
                'Japanese Rock': 'Japanese/Rock',
                'Fragile': 'Drum & Bass/Electronic',
                '\x00Abstract': 'Electronic',
                'Gothic Darkwave': 'Goth/Doom',
                'Grime': 'Electronic',
                'Country Rock': 'Rock/Folk',
                'Experimental Pop': 'Electronic/Drone',
                'Phone Work': 'Prank Calls',
                'Art Punk': '',
                'Coldwave': 'Goth/Electronic',
                'Post-Metal': 'Metal',
                'Traditional Folk': 'Folk',
                'Industrial, Goth Rock, Shoegaze, Ethereal, Experimental': 'Industrial/Goth/Shoegaze',
                'Disco-Punk': 'Disco',
                'Psychedelic': 'Psychedelic Rock',
                'Boogie': '',
                'Japan': 'Japanese',
                'Shibuya-kei': 'Indie Rock',
                'Indie Pop': 'Indie Rock',
                'Indie': 'Indie Rock',
                'Southern Rock': 'Indie Rock',
                'Club': 'R&B/Post-Punk',
                'Dance-Punk': 'House/Disco/Indie Rock',
                'Chaos Prog': 'Krautrock',
                'None': '',
                'Alternative Country': 'Indie Rock/Folk',
                'Abstract': '',
                'Dunedin Sound': 'Indie Rock',
                'BritPop': 'Rock',
                'A cappella': '',
                'Psychedelic Folk': 'Folk',
                ' Experimental': 'Electronic',
                'Proto-Punk': 'Rock',
                'Atonal': 'Jazz/Rock/Psychedelic Rock/Fusion',
                'Garage': 'Garage Rock',
                'Disco Funk': 'African/Rock/Funk/Soul',
                'World - Japan': 'Japanese/Electronic/Jazz',
                'Ethiopique Soul': 'African/Soul',
                'Avant-Pop': 'Electronic/Jazz/Rock/Ambient',
                'Punk Rock': 'Outsider',
                'Improvisation': '',
                'Dub': '',
                'Psychedelia': '',
                'Folk Rock': 'Folk',
                'Dubstep': 'Electronic',
                'Garage Punk': 'Garage Rock',
                'Synth Punk': 'Synth-Pop/Industrial/Electronic',
                'Proto': '',
                'Post': '',
                'Electro Goth': 'Goth',
                'Instrumental': 'Jazz/Bosa Nova',
                'Pop Rock': 'Pop',
                'Breaks': '',
                'Bassline': 'Electronic',
                'Beatdown': '',
                'Rhythmic Noise': '',
                'Leftfield': '',
                'Alternative Pop': '',
                'EP': 'Electronic/Techno',
                'UK Garage': 'Electronic',
                'Alternative Punk': 'Folk Punk',
                'Trance': 'Electronic',
                'Minimal': 'Contemporary Classical',
                'Experimental': '',
                'Breakbeat': 'Electronic/House',
                'Alternative & Punk': 'Indie Rock',
                'Electro-Acoustic': 'Electronic',
                'Avant-Folk': 'Folk',
                'Indie Folk': 'Folk',
                'Indiepop': 'Indie Rock',
                'Psychedelic Pop': 'Pop/Dream Pop',
                'Lo-Fi': 'Rock',
                'Afrobeat': 'African',
                'Country': 'Folk',
                'Planet E': 'Electronic/Techno',
                'Ambient House': 'Electronic'}
        update_genre(rootdir, corrections)
